### ISSUE TITLE
flow problem

### ISSUE THREAD

**Issue by ovarte** [xuhuihui/svg#1]
hello,xuhuihui! 
   用d3做的流程图里，有个问题，就是在Chrome里显示正常。但是在Firefox里流程图只显示在右上方的四分之一。找不到哪里的兼容性问题。

**Comment by xuhuihui** [comment]
![image](https://user-images.githubusercontent.com/18695789/51099835-f4ab0180-180d-11e9-880f-76601d9267b2.png)
